CREATE DATABASE APEX; USE APEX;
CREATE TABLE ENDERECO(
    id INT(11) NOT NULL AUTO_INCREMENT,
    cep CHAR(8) NOT NULL,
    numero CHAR(6) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    rua VARCHAR(100) NOT NULL,
    estado CHAR(2) NOT NULL,
    cidade VARCHAR(40),
    complemento TEXT,
    PRIMARY KEY(id)
); CREATE TABLE EMPRESA(
    id INT(11) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cnpj CHAR(14) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    endereco_id INT(11) NOT NULL,
    data_criacao DATE NOT NULL,
    telefone CHAR(14) NOT NULL,
    observacoes TEXT,
    PRIMARY KEY(id),
    CONSTRAINT fk_empresa_endereco FOREIGN KEY(endereco_id) REFERENCES ENDERECO(id) ON DELETE RESTRICT ON UPDATE CASCADE
); CREATE TABLE GALERIA(
    id INT(11) NOT NULL AUTO_INCREMENT,
    empresa_id INT(11) NOT NULL,
    imagem VARCHAR(11) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_galeria_empresa FOREIGN KEY(empresa_id) REFERENCES EMPRESA(id) ON DELETE RESTRICT ON UPDATE CASCADE
); CREATE TABLE PROFISSIONAL(
    id INT(11) NOT NULL AUTO_INCREMENT,
    empresa_id INT(11) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(150) UNIQUE NOT NULL,
    modalidade VARCHAR(10) NOT NULL,
    data_ingresso DATE NOT NULL,
    data_cadastro DATE NOT NULL DEFAULT(CURRENT_DATE),
    regra VARCHAR(10) NOT NULL,
    endereco_id INT(11) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_profissional_empresa FOREIGN KEY(empresa_id) REFERENCES EMPRESA(id) ON DELETE RESTRICT ON UPDATE CASCADE
); CREATE TABLE VEICULO(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT(11) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    marca VARCHAR(20) NOT NULL,
    ano INT(4) NOT NULL,
    quilometragem INT(6) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    tracao CHAR(3) NOT NULL,
    data_cadastro DATE NOT NULL DEFAULT(CURRENT_DATE),
    descricao TEXT,
    CONSTRAINT fk_carro_empresa FOREIGN KEY(empresa_id) REFERENCES EMPRESA(id) ON DELETE RESTRICT ON UPDATE CASCADE
); CREATE TABLE CLIENTE(
    id INT(11) NOT NULL AUTO_INCREMENT,
    empresa_id INT(11) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(14) NOT NULL UNIQUE,
    email VARCHAR(100) UNIQUE,
    data_cadastro DATETIME DEFAULT(CURRENT_DATE),
    telefone CHAR(14) NOT NULL,
    genero CHAR(1) NOT NULL,
    data_nascimento DATE NOT NULL,
    endereco_id INT(11) NOT NULL,
    observacoes TEXT,
    PRIMARY KEY(id),
    CONSTRAINT fk_cliente_empresa FOREIGN KEY(empresa_id) REFERENCES EMPRESA(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cliente_endereco FOREIGN KEY(endereco_id) REFERENCES ENDERECO(id) ON DELETE RESTRICT ON UPDATE CASCADE
); CREATE TABLE COMPRA(
    id INT(11) NOT NULL AUTO_INCREMENT,
    empresa_id INT(11) NOT NULL,
    cliente_id INT(11) NOT NULL,
    veiculo_id INT(11) NOT NULL,
    data_compra DATETIME DEFAULT(CURRENT_TIME) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_compra_empresa FOREIGN KEY(empresa_id) REFERENCES EMPRESA(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_compra_cliente FOREIGN KEY(cliente_id) REFERENCES CLIENTE(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_compra_veiculo FOREIGN KEY(veiculo_id) REFERENCES VEICULO(id) ON DELETE RESTRICT ON UPDATE CASCADE
);