    CREATE DATABASE APEX;
    USE APEX;

CREATE TABLE EMPRESA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,  
    CNPJ CHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    LOCALIZACAO VARCHAR(100) NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    TELEFONE CHAR(14) NOT NULL,
    OBSERVACOES TEXT,
    PRIMARY KEY(ID)
);

CREATE TABLE GALERIA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMPRESA_ID INT(11) NOT NULL,
    IMAGEM VARCHAR(11) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_GALERIA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PROFISSIONAL(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMPRESA_ID INT(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,  
    DATA_NASCIMENTO DATE NOT NULL,
    CPF CHAR(11) NOT NULL, 
    EMAIL VARCHAR(100) UNIQUE NOT NULL ,
    SENHA VARCHAR(150) UNIQUE NOT NULL ,
    MODALIDADE CHAR(1) NOT NULL, 
    DATA_INGRESSO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL DEFAULT (CURRENT_DATE),
    REGRA CHAR(1) NOT NULL, 
    PRIMARY KEY(ID),
    CONSTRAINT FK_PROFISSIONAL_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE VEICULO(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMPRESA_ID INT(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    ANO INT(4) NOT NULL,
    QUILOMETRAGEM INT(6) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    TRACAO CHAR(3) NOT NULL,
    DATA_CADASTRO DATE NOT NULL DEFAULT (CURRENT_DATE),
    DESCRICAO TEXT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CARRO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ENDERECO(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CEP CHAR(8) NOT NULL,
    NUMERO CHAR(6) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL, 
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(40),
    COMPLEMENTO TEXT,
    PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMPRESA_ID INT(11) NOT NULL,   
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    DATA_CADASTRO DATETIME DEFAULT (CURRENT_DATE),
    TELEFONE CHAR(14) NOT NULL,
    ENDERECO_ID INT(11) NOT NULL,
    GENERO CHAR(1) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    OBSERVACOES TEXT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CLIENTE_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE COMPRA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMPRESA_ID INT(11) NOT NULL,
    CLIENTE_ID INT(11) NOT NULL,
    VEICULO_ID INT(11) NOT NULL,
    DATA_COMPRA DATETIME DEFAULT(CURRENT_TIME) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_COMPRA_EMPRESA FOREIGN KEY (EMPRESA_ID)  REFERENCES EMPRESA(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_COMPRA_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES VEICULO(ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
